### PR TITLE
Default to "main" organization for non-supported MP

### LINKED ISSUE #75: Project not found issue when the organization is null
- The issue happens when using a previous version of `Managementportal` <2.0.0, `radar-jersey` 0.10.0, and `rest-sources-auth` 4.3.0.
- When trying to get projects or users in a project from `ProjectService`, it returns `project_not_found` error, even when the project exists.
- Logs from `rest-sources-authorizer-backend`:
```
ERROR - [404] GET projects/STAGING_PROJECT/users - project_not_found: Project STAGING_PROJECT not found in Management Portal. (HttpApplicationExceptionMapper.kt:30)
```
- Since old versions of MP doesn't have the organization structure (organization for the specific project is null), checking permissions of the user for the project causes a `project_not_found` error. This is because it checks the organization first then if the organization is null, it says the project does not exist. 
- Getting the project organization for the project throws an error here: https://github.com/RADAR-base/radar-jersey/blob/d639844ef8f4c42ea10f4caaeabd2c7f57cf93be/radar-jersey/src/main/kotlin/org/radarbase/jersey/auth/filter/PermissionFilter.kt#L88

### PR DESCRIPTION
**Pull request by blootsvoets**
Checks whether the organization path is not found. If so, by default organization "main" is used throughout the code. Intends to fix #75.

### CODE REVIEW

File: radar-jersey/src/main/kotlin/org/radarbase/jersey/service/managementportal/MPProjectService.kt [hunk 1]
```diff
@@ -56,13 +57,29 @@ class MPProjectService(
...
+                    throw ex
+                }
+            }
         }
 
         projects = CachedMap(cacheConfig) {
             mpClient.requestProjects()
+                .map { project ->
+                    if (project.organization == null) {
+                        project.copy(organization = defaultOrganization)
```
Comment (mpgxvii) [inline radar-jersey/src/main/kotlin/org/radarbase/jersey/service/managementportal/MPProjectService.kt:78]: I remember there's also an `organization` key in the old MP versions. Would we also map those to `main` organization?

**Review by mpgxvii — APPROVED** [review]
LGTM, thanks so much!

File: radar-jersey/src/main/kotlin/org/radarbase/jersey/service/managementportal/MPProjectService.kt (hunk 1 above)
Comment (blootsvoets) [reply radar-jersey/src/main/kotlin/org/radarbase/jersey/service/managementportal/MPProjectService.kt:78]: ah good point... at that point it would probably throw a deserialisation error. Let me check.

Comment (mpgxvii) [reply radar-jersey/src/main/kotlin/org/radarbase/jersey/service/managementportal/MPProjectService.kt:79]: Ok I see, thanks for the updates!
